openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/companies:
    get:
      summary: 'List all companies.'
      operationId: listAllCompanies
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Retrieved companies'
                  data:
                    -
                      name: "O'Hara-Beatty"
                      city: Collierville
                      state: side
                      country: Ghana
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E11.tmp'
                      extension: tmp
                    -
                      name: Tromp-Ritchie
                      city: 'Port Ayana'
                      state: furt
                      country: Uzbekistan
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E12.tmp'
                      extension: tmp
                    -
                      name: 'Streich PLC'
                      city: 'Port Nyasiaburgh'
                      state: stad
                      country: Guyana
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E13.tmp'
                      extension: tmp
                    -
                      name: 'Roob LLC'
                      city: Leslieland
                      state: mouth
                      country: 'New Zealand'
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                      extension: tmp
                    -
                      name: Woolies
                      city: Yorke
                      state: Liquid
                      country: Atlantis
                      logo_path: null
                      extension: null
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Retrieved companies'
                  data:
                    type: array
                    example:
                      -
                        name: "O'Hara-Beatty"
                        city: Collierville
                        state: side
                        country: Ghana
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E11.tmp'
                        extension: tmp
                      -
                        name: Tromp-Ritchie
                        city: 'Port Ayana'
                        state: furt
                        country: Uzbekistan
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E12.tmp'
                        extension: tmp
                      -
                        name: 'Streich PLC'
                        city: 'Port Nyasiaburgh'
                        state: stad
                        country: Guyana
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E13.tmp'
                        extension: tmp
                      -
                        name: 'Roob LLC'
                        city: Leslieland
                        state: mouth
                        country: 'New Zealand'
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                        extension: tmp
                      -
                        name: Woolies
                        city: Yorke
                        state: Liquid
                        country: Atlantis
                        logo_path: null
                        extension: null
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: "O'Hara-Beatty"
                        city:
                          type: string
                          example: Collierville
                        state:
                          type: string
                          example: side
                        country:
                          type: string
                          example: Ghana
                        logo_path:
                          type: string
                          example: 'C:\Users\Lori\AppData\Local\Temp\fak5E11.tmp'
                        extension:
                          type: string
                          example: tmp
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Add a company to the database.'
      operationId: addACompanyToTheDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/v1/companies/{id}':
    get:
      summary: 'Display a single company.'
      operationId: displayASingleCompany
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server Error'
                properties:
                  message:
                    type: string
                    example: 'Server Error'
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified company in the database.'
      operationId: updateTheSpecifiedCompanyInTheDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Soft delete the specified company from the database'
      operationId: softDeleteTheSpecifiedCompanyFromTheDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the company.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/positions:
    get:
      summary: 'List all positions'
      operationId: listAllPositions
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Retrieved positions'
                  data:
                    -
                      company:
                        name: 'Roob LLC'
                        city: Leslieland
                        state: mouth
                        country: 'New Zealand'
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                        extension: tmp
                      start: '1975-05-25'
                      end: '2015-06-28'
                      title: 'Recreational Vehicle Service Technician'
                      description: 'Delectus qui voluptatibus voluptatem ut fuga.'
                      min_salary: 45011
                      max_salary: 100280
                      currency: TMT
                      benefits: 'et quod eius quo laudantium'
                      requirements: 'ea id ratione quis dignissimos eaque quia incidunt sint cumque'
                      type: unde
                    -
                      company:
                        name: 'Roob LLC'
                        city: Leslieland
                        state: mouth
                        country: 'New Zealand'
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                        extension: tmp
                      start: '1994-04-10'
                      end: '2006-02-02'
                      title: 'Instrument Sales Representative'
                      description: 'Enim sapiente non aut fuga in rem.'
                      min_salary: 52046
                      max_salary: 111734
                      currency: GMD
                      benefits: 'vero quibusdam molestiae reiciendis sapiente'
                      requirements: 'laboriosam voluptate ut aut et quia sint qui magni dolores'
                      type: vitae
                    -
                      company:
                        name: 'Roob LLC'
                        city: Leslieland
                        state: mouth
                        country: 'New Zealand'
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                        extension: tmp
                      start: '1999-06-16'
                      end: '2006-06-27'
                      title: Bartender
                      description: 'Eum molestias qui alias qui maxime aliquam.'
                      min_salary: 44122
                      max_salary: 112760
                      currency: CZK
                      benefits: 'ipsam cupiditate dolorum id eaque'
                      requirements: 'numquam autem et eius ut impedit sit distinctio cupiditate delectus'
                      type: vitae
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Retrieved positions'
                  data:
                    type: array
                    example:
                      -
                        company:
                          name: 'Roob LLC'
                          city: Leslieland
                          state: mouth
                          country: 'New Zealand'
                          logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                          extension: tmp
                        start: '1975-05-25'
                        end: '2015-06-28'
                        title: 'Recreational Vehicle Service Technician'
                        description: 'Delectus qui voluptatibus voluptatem ut fuga.'
                        min_salary: 45011
                        max_salary: 100280
                        currency: TMT
                        benefits: 'et quod eius quo laudantium'
                        requirements: 'ea id ratione quis dignissimos eaque quia incidunt sint cumque'
                        type: unde
                      -
                        company:
                          name: 'Roob LLC'
                          city: Leslieland
                          state: mouth
                          country: 'New Zealand'
                          logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                          extension: tmp
                        start: '1994-04-10'
                        end: '2006-02-02'
                        title: 'Instrument Sales Representative'
                        description: 'Enim sapiente non aut fuga in rem.'
                        min_salary: 52046
                        max_salary: 111734
                        currency: GMD
                        benefits: 'vero quibusdam molestiae reiciendis sapiente'
                        requirements: 'laboriosam voluptate ut aut et quia sint qui magni dolores'
                        type: vitae
                      -
                        company:
                          name: 'Roob LLC'
                          city: Leslieland
                          state: mouth
                          country: 'New Zealand'
                          logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                          extension: tmp
                        start: '1999-06-16'
                        end: '2006-06-27'
                        title: Bartender
                        description: 'Eum molestias qui alias qui maxime aliquam.'
                        min_salary: 44122
                        max_salary: 112760
                        currency: CZK
                        benefits: 'ipsam cupiditate dolorum id eaque'
                        requirements: 'numquam autem et eius ut impedit sit distinctio cupiditate delectus'
                        type: vitae
                    items:
                      type: object
                      properties:
                        company:
                          type: object
                          properties:
                            name:
                              type: string
                              example: 'Roob LLC'
                            city:
                              type: string
                              example: Leslieland
                            state:
                              type: string
                              example: mouth
                            country:
                              type: string
                              example: 'New Zealand'
                            logo_path:
                              type: string
                              example: 'C:\Users\Lori\AppData\Local\Temp\fak5E43.tmp'
                            extension:
                              type: string
                              example: tmp
                        start:
                          type: string
                          example: '1975-05-25'
                        end:
                          type: string
                          example: '2015-06-28'
                        title:
                          type: string
                          example: 'Recreational Vehicle Service Technician'
                        description:
                          type: string
                          example: 'Delectus qui voluptatibus voluptatem ut fuga.'
                        min_salary:
                          type: integer
                          example: 45011
                        max_salary:
                          type: integer
                          example: 100280
                        currency:
                          type: string
                          example: TMT
                        benefits:
                          type: string
                          example: 'et quod eius quo laudantium'
                        requirements:
                          type: string
                          example: 'ea id ratione quis dignissimos eaque quia incidunt sint cumque'
                        type:
                          type: string
                          example: unde
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiV1Positions
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/v1/positions/{id}':
    get:
      summary: ''
      operationId: getApiV1PositionsId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiV1PositionsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1PositionsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the position.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
