openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/regions:
    get:
      summary: 'Retrieve all regions'
      operationId: retrieveAllRegions
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Regions retrieved successfully'
                  data:
                    -
                      id: 1
                      name: Africa
                      created_at: '2024-09-19T02:55:52.000000Z'
                      updated_at: '2024-09-19T02:55:52.000000Z'
                    -
                      id: 2
                      name: Americas
                      created_at: '2024-09-19T02:55:52.000000Z'
                      updated_at: '2024-09-19T02:55:52.000000Z'
                    -
                      id: 3
                      name: Asia
                      created_at: '2024-09-19T02:55:52.000000Z'
                      updated_at: '2024-09-19T02:55:52.000000Z'
                    -
                      id: 4
                      name: Europe
                      created_at: '2024-09-19T02:55:52.000000Z'
                      updated_at: '2024-09-19T02:55:52.000000Z'
                    -
                      id: 5
                      name: Oceania
                      created_at: '2024-09-19T02:55:52.000000Z'
                      updated_at: '2024-09-19T02:55:52.000000Z'
                    -
                      id: 6
                      name: Polar
                      created_at: '2024-09-19T02:55:52.000000Z'
                      updated_at: '2024-09-19T02:55:52.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Regions retrieved successfully'
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: Africa
                        created_at: '2024-09-19T02:55:52.000000Z'
                        updated_at: '2024-09-19T02:55:52.000000Z'
                      -
                        id: 2
                        name: Americas
                        created_at: '2024-09-19T02:55:52.000000Z'
                        updated_at: '2024-09-19T02:55:52.000000Z'
                      -
                        id: 3
                        name: Asia
                        created_at: '2024-09-19T02:55:52.000000Z'
                        updated_at: '2024-09-19T02:55:52.000000Z'
                      -
                        id: 4
                        name: Europe
                        created_at: '2024-09-19T02:55:52.000000Z'
                        updated_at: '2024-09-19T02:55:52.000000Z'
                      -
                        id: 5
                        name: Oceania
                        created_at: '2024-09-19T02:55:52.000000Z'
                        updated_at: '2024-09-19T02:55:52.000000Z'
                      -
                        id: 6
                        name: Polar
                        created_at: '2024-09-19T02:55:52.000000Z'
                        updated_at: '2024-09-19T02:55:52.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Africa
                        created_at:
                          type: string
                          example: '2024-09-19T02:55:52.000000Z'
                        updated_at:
                          type: string
                          example: '2024-09-19T02:55:52.000000Z'
      tags:
        - Endpoints
      security: []
  '/api/v1/regions/{id}':
    get:
      summary: 'Retrieve a single region'
      operationId: retrieveASingleRegion
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Region retrieved successfully.'
                  data:
                    -
                      id: 1
                      name: Africa
                      created_at: '2024-09-19T02:55:52.000000Z'
                      updated_at: '2024-09-19T02:55:52.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Region retrieved successfully.'
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: Africa
                        created_at: '2024-09-19T02:55:52.000000Z'
                        updated_at: '2024-09-19T02:55:52.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Africa
                        created_at:
                          type: string
                          example: '2024-09-19T02:55:52.000000Z'
                        updated_at:
                          type: string
                          example: '2024-09-19T02:55:52.000000Z'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the region.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/companies/trash/{id}':
    get:
      summary: 'Restore the specified soft deleted company from trash.'
      operationId: restoreTheSpecifiedSoftDeletedCompanyFromTrash
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Company with id: perspiciatis restored'
                  data: perspiciatis
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Company with id: perspiciatis restored'
                  data:
                    type: string
                    example: perspiciatis
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the trash.'
        example: perspiciatis
        required: true
        schema:
          type: string
  /api/v1/companies:
    get:
      summary: 'List all companies.'
      operationId: listAllCompanies
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Retrieved companies'
                  data:
                    -
                      name: 'Berge, Murazik and Graham'
                      city: Schmelerfort
                      state: land
                      country: Mongolia
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3833.tmp'
                      extension: tmp
                    -
                      name: Lakin-Effertz
                      city: Vivahaven
                      state: burgh
                      country: Gibraltar
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3834.tmp'
                      extension: tmp
                    -
                      name: 'Robel Ltd'
                      city: 'Lake Helga'
                      state: town
                      country: Norway
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3835.tmp'
                      extension: tmp
                    -
                      name: 'Weber, Pouros and Heidenreich'
                      city: 'South Horaciohaven'
                      state: bury
                      country: Poland
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3836.tmp'
                      extension: tmp
                    -
                      name: 'Champlin Inc'
                      city: Michealfort
                      state: town
                      country: Austria
                      logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3837.tmp'
                      extension: tmp
                    -
                      name: Woolies
                      city: York
                      state: Liquid
                      country: Atlantis
                      logo_path: null
                      extension: null
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Retrieved companies'
                  data:
                    type: array
                    example:
                      -
                        name: 'Berge, Murazik and Graham'
                        city: Schmelerfort
                        state: land
                        country: Mongolia
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3833.tmp'
                        extension: tmp
                      -
                        name: Lakin-Effertz
                        city: Vivahaven
                        state: burgh
                        country: Gibraltar
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3834.tmp'
                        extension: tmp
                      -
                        name: 'Robel Ltd'
                        city: 'Lake Helga'
                        state: town
                        country: Norway
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3835.tmp'
                        extension: tmp
                      -
                        name: 'Weber, Pouros and Heidenreich'
                        city: 'South Horaciohaven'
                        state: bury
                        country: Poland
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3836.tmp'
                        extension: tmp
                      -
                        name: 'Champlin Inc'
                        city: Michealfort
                        state: town
                        country: Austria
                        logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3837.tmp'
                        extension: tmp
                      -
                        name: Woolies
                        city: York
                        state: Liquid
                        country: Atlantis
                        logo_path: null
                        extension: null
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 'Berge, Murazik and Graham'
                        city:
                          type: string
                          example: Schmelerfort
                        state:
                          type: string
                          example: land
                        country:
                          type: string
                          example: Mongolia
                        logo_path:
                          type: string
                          example: 'C:\Users\Lori\AppData\Local\Temp\fak3833.tmp'
                        extension:
                          type: string
                          example: tmp
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Add a company to the database.'
      operationId: addACompanyToTheDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/v1/companies/{id}':
    get:
      summary: 'Display a single company.'
      operationId: displayASingleCompany
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Retrieved company'
                  data:
                    name: 'Berge, Murazik and Graham'
                    city: Schmelerfort
                    state: land
                    country: Mongolia
                    logo_path: 'C:\Users\Lori\AppData\Local\Temp\fak3833.tmp'
                    extension: tmp
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Retrieved company'
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Berge, Murazik and Graham'
                      city:
                        type: string
                        example: Schmelerfort
                      state:
                        type: string
                        example: land
                      country:
                        type: string
                        example: Mongolia
                      logo_path:
                        type: string
                        example: 'C:\Users\Lori\AppData\Local\Temp\fak3833.tmp'
                      extension:
                        type: string
                        example: tmp
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified company in the database.'
      operationId: updateTheSpecifiedCompanyInTheDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be between 2 and 255 characters.'
                  example: grf
                city:
                  type: string
                  description: 'Must be between 2 and 255 characters.'
                  example: ub
                state:
                  type: string
                  description: 'Must be between 2 and 16 characters.'
                  example: yw
                country:
                  type: string
                  description: 'Must be between 2 and 255 characters.'
                  example: flp
                logo:
                  type: string
                  format: binary
                  description: 'Must be an image.'
              required:
                - name
      security: []
    delete:
      summary: 'Soft delete the specified company from the database'
      operationId: softDeleteTheSpecifiedCompanyFromTheDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the company.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
